export const BRANDS = {
  men: [
    "Gucci",
    "Boss",
    "K-Way",
    "Lacoste",
    "Levi's",
    "Tommy Hilfiger",
    "Jack & Jones",
    "Polo Ralph Lauren",
    "Balenciaga",
    "Marvin&Co",
    "Schott",
    "Sandro",
  ],
  women: [
    "Maje",
    "Sandro",
    "Claudie Pierlot",
    "The Kooples",
    "American Vintage",
    "Zadig&Voltaire",
    "Soeur",
    "Sessùn",
    "Tommy Hilfiger",
    "Morgan",
    "IKKS Women",
  ],
};

export const CATEGORIES = {
  men: [
    "t-shirts et polos",
    "vestes et manteaux",
    "pantalons",
    "jeans",
    "chemises",
    "sweats",
    "pulls et gilets",
    "sous-vêtements",
    "tenues de sport",
    "doudounes",
    "shorts et bermudas",
    "shorts et slips de bain",
  ],
  women: [
    "chemises et blouses",
    "jeans",
    "jupes",
    "lingerie",
    "maillots de bain",
    "pantalons",
    "pulls et gilets",
    "robes",
    "sweats et hoodies",
    "tops et t-shirts",
    "vestes et manteaux",
  ],
};
