name: Run Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout/@v4

      - name: Set up Node
        uses: actions/setup-node/@v4
        with:
          node-version: "20"

      - name: Install dependencies
        uses: npm ci

      - name: Run tests
        uses: npm test
